ARG INTEROP_BASE_IMAGE
FROM ${INTEROP_BASE_IMAGE}

ARG INTEROP_PEER
LABEL io.github.mundanej.mjo.interop.peer="${INTEROP_PEER}"
LABEL io.github.mundanej.mjo.interop.stage="g4-script-scaffold"

WORKDIR /interop
COPY interop/container/entrypoint.sh /usr/local/bin/interop-peer-entrypoint

ENTRYPOINT ["/usr/local/bin/interop-peer-entrypoint"]
CMD ["help"]
