package io.github.mundanej.mjo.codegen;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import io.github.mundanej.mjo.idl.java.mapping.IdlJavaMapper;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedConstant;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedConstantScope;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedName;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedType;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedTypeKind;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappingMode;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappingModel;
import io.github.mundanej.mjo.idl.parser.IdlParseResult;
import io.github.mundanej.mjo.idl.parser.IdlParser;
import io.github.mundanej.mjo.idl.semantics.IdlSemanticAnalyzer;
import io.github.mundanej.mjo.idl.semantics.IdlSemanticModel;
import io.github.mundanej.mjo.idl.semantics.IdlSemanticResult;
import io.github.mundanej.mjo.testkit.FixtureSet;
import io.github.mundanej.mjo.testkit.GoldenAssertions;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import javax.tools.JavaCompiler;
import javax.tools.ToolProvider;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/** Unit and generated-source tests for {@link JavaSourceGenerator}. */
@Tag("unit")
@Tag("generated-code")
final class JavaSourceGeneratorTest {

  private final IdlParser parser = new IdlParser();
  private final IdlSemanticAnalyzer analyzer = new IdlSemanticAnalyzer();
  private final IdlJavaMapper mapper = new IdlJavaMapper();
  private final JavaSourceGenerator generator = new JavaSourceGenerator();
  private static final List<String> FORBIDDEN_GENERATED_SOURCE_TOKENS =
      List.of(
          "org.omg",
          "Helper",
          "Holder",
          "Stub",
          "Skeleton",
          "POA",
          "io.github.mundanej.mjo.cdr",
          "io.github.mundanej.mjo.orb",
          "java.lang.reflect",
          "ServiceLoader",
          "ClassLoader",
          "Proxy",
          "java.lang.invoke",
          "ObjectInputStream",
          "ObjectOutputStream",
          "Externalizable",
          "Serializable",
          "System.exit",
          "ProcessBuilder",
          "Runtime.getRuntime",
          "finalize",
          "sun.",
          "jdk.internal.");

  @TempDir private Path tempDir;

  @Test
  void generatesLegacyAndModernGoldenSources() {
    JavaMappingModel legacy = mapping(JavaMappingMode.LEGACY_COMPATIBILITY);
    JavaMappingModel modern = mapping(JavaMappingMode.MODERN);

    List<GeneratedJavaSource> legacySources = generator.generate(legacy);
    List<GeneratedJavaSource> modernSources = generator.generate(modern);

    assertEquals(legacySources, generator.generate(legacy));
    assertEquals(
        List.of(
            "demo/Bad.java",
            "demo/Color.java",
            "demo/IdlConstants.java",
            "demo/Point.java",
            "demo/Shape.java"),
        legacySources.stream().map(GeneratedJavaSource::sourcePath).toList());
    GoldenAssertions.assertTextEquals(
        "legacy constants",
        """
        // Generated by mundane-java-orb G6-160.
        // Source IDL: codegen-test.idl
        // Mapping mode: LEGACY_COMPATIBILITY
        // Compatibility profile: compile-safe minimal IDL-to-Java slice.

        package demo;

        public final class IdlConstants {

          private IdlConstants() {}

          public static final int BASE = 7;
          public static final demo.Color FAVORITE = demo.Color.GREEN;
        }
        """,
        sourceText(legacySources, "demo/IdlConstants.java"));
    GoldenAssertions.assertTextEquals(
        "modern constants",
        """
        // Generated by mundane-java-orb G6-160.
        // Source IDL: codegen-test.idl
        // Mapping mode: MODERN
        // Compatibility profile: compile-safe minimal IDL-to-Java slice.

        package modern.demo;

        public final class IdlConstants {

          private IdlConstants() {}

          public static final int BASE = 7;
          public static final modern.demo.Color FAVORITE = modern.demo.Color.GREEN;
        }
        """,
        sourceText(modernSources, "modern/demo/IdlConstants.java"));
  }

  @Test
  void generatedSourcesCompileAndAvoidRuntimeDependencies() throws Exception {
    List<GeneratedJavaSource> sources = new ArrayList<>();
    sources.addAll(generator.generate(mapping(JavaMappingMode.LEGACY_COMPATIBILITY)));
    sources.addAll(generator.generate(mapping(JavaMappingMode.MODERN)));

    String allSource =
        sources.stream().map(GeneratedJavaSource::sourceText).reduce("", String::concat);
    assertNoForbiddenGeneratedSourceTokens(allSource);
    compile(sources);
  }

  @Test
  void generatesHelloGoldenSourcesFromIdlFixture() throws Exception {
    IdlSemanticModel semanticModel =
        semanticModel("hello/hello.idl", idlFixtures().readUtf8("hello/hello.idl"));

    List<GeneratedJavaSource> legacySources =
        generator.generate(mapper.map(semanticModel, JavaMappingMode.LEGACY_COMPATIBILITY));
    List<GeneratedJavaSource> modernSources =
        generator.generate(mapper.map(semanticModel, JavaMappingMode.MODERN));
    List<GeneratedJavaSource> allSources = new ArrayList<>();
    allSources.addAll(legacySources);
    allSources.addAll(modernSources);

    assertEquals(List.of("hello/Greeter.java"), sourcePaths(legacySources));
    assertEquals(List.of("modern/hello/Greeter.java"), sourcePaths(modernSources));
    GoldenAssertions.assertTextEquals(
        "hello legacy Greeter",
        goldenFixtures().readUtf8("hello/legacy/hello/Greeter.java"),
        sourceText(legacySources, "hello/Greeter.java"));
    GoldenAssertions.assertTextEquals(
        "hello modern Greeter",
        goldenFixtures().readUtf8("hello/modern/modern/hello/Greeter.java"),
        sourceText(modernSources, "modern/hello/Greeter.java"));
    assertNoForbiddenGeneratedSourceTokens(
        allSources.stream().map(GeneratedJavaSource::sourceText).reduce("", String::concat));
    compile(allSources);
  }

  @Test
  void generatesCompileSafeSourcesFromApprovedRmiGeneratedIdlFixture() throws Exception {
    IdlSemanticModel semanticModel = semanticModel("rmi-generated.idl", rmiGeneratedIdlFixture());

    List<GeneratedJavaSource> sources =
        generator.generate(mapper.map(semanticModel, JavaMappingMode.LEGACY_COMPATIBILITY));

    assertEquals(
        List.of("example/calc/Calculator.java", "example/calc/CalculatorProblem.java"),
        sourcePaths(sources));
    GoldenAssertions.assertTextEquals(
        "RMI generated IDL Calculator",
        """
        // Generated by mundane-java-orb G6-160.
        // Source IDL: rmi-generated.idl
        // Mapping mode: LEGACY_COMPATIBILITY
        // Compatibility profile: compile-safe minimal IDL-to-Java slice.

        package example.calc;

        public interface Calculator {

          int add(int left, int right);

          java.lang.String describe(java.lang.String name) throws example.calc.CalculatorProblem;

          void clear();
        }
        """,
        sourceText(sources, "example/calc/Calculator.java"));
    assertNoForbiddenGeneratedSourceTokens(
        sources.stream().map(GeneratedJavaSource::sourceText).reduce("", String::concat));
    compile(sources);
  }

  @Test
  void generatedSourceValuesValidateAndExposePaths() {
    GeneratedJavaSource source = new GeneratedJavaSource("demo", "Thing", "package demo;\n");

    assertEquals("demo/Thing.java", source.sourcePath());
    assertThrows(
        IllegalArgumentException.class, () -> new GeneratedJavaSource("", "", "class X {}\n"));
    assertThrows(IllegalArgumentException.class, () -> new GeneratedJavaSource("", "X", " "));
  }

  @Test
  void generatedSourcesAvoidConstantHolderNameCollisions() throws Exception {
    IdlSemanticModel semanticModel =
        semanticModel(
            """
            module Demo {
              const long VALUE = 1;
              struct IdlConstants { long x; };
            };
            """);

    List<GeneratedJavaSource> sources =
        generator.generate(mapper.map(semanticModel, JavaMappingMode.LEGACY_COMPATIBILITY));

    assertEquals(
        List.of("demo/IdlConstants.java", "demo/IdlConstants_.java"),
        sources.stream().map(GeneratedJavaSource::sourcePath).toList());
    compile(sources);
  }

  @Test
  void rejectsDuplicateGeneratedSourcePaths() {
    JavaMappingModel model =
        new JavaMappingModel(
            JavaMappingMode.LEGACY_COMPATIBILITY,
            "duplicate.idl",
            List.of(
                new JavaMappedType(
                    JavaMappedTypeKind.STRUCT,
                    new JavaMappedName("demo", "Thing"),
                    List.of(),
                    List.of(),
                    List.of(),
                    List.of())),
            List.of(
                new JavaMappedConstantScope(
                    new JavaMappedName("demo", "Thing"),
                    List.of(new JavaMappedConstant("int", "VALUE", "1")))));

    IllegalArgumentException exception =
        assertThrows(IllegalArgumentException.class, () -> generator.generate(model));
    assertEquals("Duplicate generated Java source path: demo/Thing.java", exception.getMessage());
  }

  private JavaMappingModel mapping(JavaMappingMode mode) {
    return mapper.map(semanticModel(), mode);
  }

  private IdlSemanticModel semanticModel() {
    return semanticModel(
        """
        module Demo {
          const long BASE = 7;
          enum Color { RED, GREEN };
          const Color FAVORITE = Color::GREEN;
          struct Point { long x; string label; };
          exception Bad { string reason; };
          interface Shape {
            readonly attribute string name;
            attribute long size;
            Point move(in Point value, out long count) raises (Bad);
          };
        };
        """);
  }

  private IdlSemanticModel semanticModel(String source) {
    return semanticModel("codegen-test.idl", source);
  }

  private IdlSemanticModel semanticModel(String sourceName, String source) {
    IdlParseResult parseResult = parser.parse(sourceName, source);
    assertFalse(parseResult.hasErrors(), () -> parseResult.diagnostics().toString());
    IdlSemanticResult semanticResult =
        analyzer.analyze(parseResult.translationUnit().orElseThrow());
    assertFalse(semanticResult.hasErrors(), () -> semanticResult.diagnostics().toString());
    return semanticResult.model().orElseThrow();
  }

  private static List<String> sourcePaths(List<GeneratedJavaSource> sources) {
    return sources.stream().map(GeneratedJavaSource::sourcePath).toList();
  }

  private static String sourceText(List<GeneratedJavaSource> sources, String sourcePath) {
    return sources.stream()
        .filter(source -> source.sourcePath().equals(sourcePath))
        .findFirst()
        .orElseThrow()
        .sourceText();
  }

  private static void assertNoForbiddenGeneratedSourceTokens(String sourceText) {
    List<String> violations =
        FORBIDDEN_GENERATED_SOURCE_TOKENS.stream().filter(sourceText::contains).toList();

    assertEquals(List.of(), violations, "Generated source contains forbidden architecture tokens");
  }

  private static FixtureSet idlFixtures() {
    return new FixtureSet(findRepositoryRoot().resolve("interop/idl"));
  }

  private static FixtureSet goldenFixtures() throws Exception {
    URL resource = JavaSourceGeneratorTest.class.getResource("/golden-source");
    assertNotNull(resource, "golden-source test resource root");
    return new FixtureSet(Path.of(resource.toURI()));
  }

  private static String rmiGeneratedIdlFixture() throws Exception {
    return Files.readString(
        findRepositoryRoot()
            .resolve("modules/corba-rmi-iiop/src/test/resources/rmi-generated-idl/calculator.idl"));
  }

  private static Path findRepositoryRoot() {
    Path directory = Path.of("").toAbsolutePath().normalize();
    while (directory != null) {
      if (Files.isRegularFile(directory.resolve("AGENT.md"))
          && Files.isDirectory(directory.resolve("modules"))) {
        return directory;
      }
      directory = directory.getParent();
    }
    throw new IllegalStateException("Could not locate repository root from test working directory");
  }

  private void compile(List<GeneratedJavaSource> sources) throws Exception {
    Path sourceRoot = Files.createDirectories(tempDir.resolve("generated-src"));
    Path classOutput = Files.createDirectories(tempDir.resolve("generated-classes"));
    List<String> arguments = new ArrayList<>();
    arguments.add("-d");
    arguments.add(classOutput.toString());
    for (GeneratedJavaSource source : sources) {
      Path sourceFile = sourceRoot.resolve(source.sourcePath());
      Path parent = sourceFile.getParent();
      if (parent != null) {
        Files.createDirectories(parent);
      }
      Files.writeString(sourceFile, source.sourceText(), StandardCharsets.UTF_8);
      arguments.add(sourceFile.toString());
    }

    JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
    assertNotNull(compiler, "Generated-source compilation requires a JDK compiler");
    assertEquals(0, compiler.run(null, null, null, arguments.toArray(String[]::new)));
  }
}
