package io.github.mundanej.mjo.codegen;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import io.github.mundanej.mjo.idl.java.mapping.IdlJavaMapper;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedAttribute;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedConstant;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedConstantScope;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedField;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedName;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedOperation;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedParameter;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedType;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedTypeKind;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappingMode;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappingModel;
import io.github.mundanej.mjo.idl.parser.IdlParseResult;
import io.github.mundanej.mjo.idl.parser.IdlParser;
import io.github.mundanej.mjo.idl.semantics.IdlSemanticAnalyzer;
import io.github.mundanej.mjo.idl.semantics.IdlSemanticModel;
import io.github.mundanej.mjo.idl.semantics.IdlSemanticResult;
import io.github.mundanej.mjo.testkit.FixtureSet;
import io.github.mundanej.mjo.testkit.GoldenAssertions;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import javax.tools.JavaCompiler;
import javax.tools.ToolProvider;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/** Unit and generated-source tests for {@link JavaSourceGenerator}. */
@Tag("unit")
@Tag("generated-code")
final class JavaSourceGeneratorTest {

  private final IdlParser parser = new IdlParser();
  private final IdlSemanticAnalyzer analyzer = new IdlSemanticAnalyzer();
  private final IdlJavaMapper mapper = new IdlJavaMapper();
  private final JavaSourceGenerator generator = new JavaSourceGenerator();
  private static final List<String> FORBIDDEN_GENERATED_SOURCE_TOKENS =
      List.of(
          "org.omg",
          "Skeleton",
          "io.github.mundanej.mjo.cdr",
          "io.github.mundanej.mjo.orb",
          "java.lang.reflect",
          "ServiceLoader",
          "ClassLoader",
          "Proxy",
          "java.lang.invoke",
          "ObjectInputStream",
          "ObjectOutputStream",
          "Externalizable",
          "Serializable",
          "System.exit",
          "ProcessBuilder",
          "Runtime.getRuntime",
          "finalize",
          "sun.",
          "jdk.internal.");

  @TempDir private Path tempDir;

  @Test
  void generatesLegacyAndModernGoldenSources() {
    JavaMappingModel legacy = mapping(JavaMappingMode.LEGACY_COMPATIBILITY);
    JavaMappingModel modern = mapping(JavaMappingMode.MODERN);

    List<GeneratedJavaSource> legacySources = generator.generate(legacy);
    List<GeneratedJavaSource> modernSources = generator.generate(modern);

    assertEquals(legacySources, generator.generate(legacy));
    assertEquals(
        List.of(
            "demo/Bad.java",
            "demo/BadHelper.java",
            "demo/BadHolder.java",
            "demo/Color.java",
            "demo/ColorHelper.java",
            "demo/ColorHolder.java",
            "demo/IdlConstants.java",
            "demo/LongHolder.java",
            "demo/Point.java",
            "demo/PointHelper.java",
            "demo/PointHolder.java",
            "demo/Shape.java",
            "demo/ShapeHelper.java",
            "demo/ShapeHolder.java",
            "demo/ShapePOA.java",
            "demo/_ShapeStub.java"),
        legacySources.stream().map(GeneratedJavaSource::sourcePath).toList());
    GoldenAssertions.assertTextEquals(
        "legacy constants",
        """
        // Generated by mundane-java-orb G6-160.
        // Source IDL: codegen-test.idl
        // Mapping mode: LEGACY_COMPATIBILITY
        // Compatibility profile: compile-safe minimal IDL-to-Java slice.

        package demo;

        public final class IdlConstants {

          private IdlConstants() {}

          public static final int BASE = 7;
          public static final demo.Color FAVORITE = demo.Color.GREEN;
        }
        """,
        sourceText(legacySources, "demo/IdlConstants.java"));
    GoldenAssertions.assertTextEquals(
        "modern constants",
        """
        // Generated by mundane-java-orb G6-160.
        // Source IDL: codegen-test.idl
        // Mapping mode: MODERN
        // Compatibility profile: compile-safe minimal IDL-to-Java slice.

        package modern.demo;

        public final class IdlConstants {

          private IdlConstants() {}

          public static final int BASE = 7;
          public static final modern.demo.Color FAVORITE = modern.demo.Color.GREEN;
        }
        """,
        sourceText(modernSources, "modern/demo/IdlConstants.java"));
  }

  @Test
  void generatedSourcesCompileAndAvoidRuntimeDependencies() throws Exception {
    List<GeneratedJavaSource> sources = new ArrayList<>();
    sources.addAll(generator.generate(mapping(JavaMappingMode.LEGACY_COMPATIBILITY)));
    sources.addAll(generator.generate(mapping(JavaMappingMode.MODERN)));

    String allSource =
        sources.stream().map(GeneratedJavaSource::sourceText).reduce("", String::concat);
    assertNoForbiddenGeneratedSourceTokens(allSource);
    compile(sources);
  }

  @Test
  void rendersDefaultPackageValueObjectsExceptionsAttributesAndThrows() throws Exception {
    JavaMappingModel model =
        new JavaMappingModel(
            JavaMappingMode.LEGACY_COMPATIBILITY,
            "manual-render.idl",
            List.of(
                new JavaMappedType(
                    JavaMappedTypeKind.STRUCT,
                    new JavaMappedName("", "Point"),
                    List.of(
                        new JavaMappedField("int", "x"),
                        new JavaMappedField("java.lang.String", "label")),
                    List.of(),
                    List.of(),
                    List.of()),
                new JavaMappedType(
                    JavaMappedTypeKind.EXCEPTION,
                    new JavaMappedName("", "Bad"),
                    List.of(new JavaMappedField("java.lang.String", "reason")),
                    List.of(),
                    List.of(),
                    List.of()),
                new JavaMappedType(
                    JavaMappedTypeKind.INTERFACE,
                    new JavaMappedName("", "Shape"),
                    List.of(),
                    List.of(),
                    List.of(
                        new JavaMappedOperation(
                            "Point",
                            "move",
                            List.of(new JavaMappedParameter("Point", "value")),
                            List.of("Bad"))),
                    List.of(
                        new JavaMappedAttribute("java.lang.String", "name", true),
                        new JavaMappedAttribute("int", "size", false)))),
            List.of());

    List<GeneratedJavaSource> sources = generator.generate(model);

    assertEquals(
        List.of(
            "Bad.java",
            "BadHelper.java",
            "BadHolder.java",
            "Point.java",
            "PointHelper.java",
            "PointHolder.java",
            "Shape.java",
            "ShapeHelper.java",
            "ShapeHolder.java",
            "ShapePOA.java",
            "_ShapeStub.java"),
        sourcePaths(sources));
    GoldenAssertions.assertTextEquals(
        "default package value object",
        """
        // Generated by mundane-java-orb G6-160.
        // Source IDL: manual-render.idl
        // Mapping mode: LEGACY_COMPATIBILITY
        // Compatibility profile: compile-safe minimal IDL-to-Java slice.

        public final class Point {

          public final int x;

          public final java.lang.String label;

          public Point(int x, java.lang.String label) {
            this.x = x;
            this.label = label;
          }
        }
        """,
        sourceText(sources, "Point.java"));
    assertContains(sourceText(sources, "Bad.java"), "public class Bad extends java.lang.Exception");
    assertContains(sourceText(sources, "Bad.java"), "super();");
    assertContains(sourceText(sources, "Shape.java"), "java.lang.String getName();");
    assertContains(sourceText(sources, "Shape.java"), "int getSize();");
    assertContains(sourceText(sources, "Shape.java"), "void setSize(int size);");
    assertContains(sourceText(sources, "Shape.java"), "Point move(Point value) throws Bad;");
    compile(sources);
  }

  @Test
  void generatesHelloGoldenSourcesFromIdlFixture() throws Exception {
    IdlSemanticModel semanticModel =
        semanticModel("hello/hello.idl", idlFixtures().readUtf8("hello/hello.idl"));

    List<GeneratedJavaSource> legacySources =
        generator.generate(mapper.map(semanticModel, JavaMappingMode.LEGACY_COMPATIBILITY));
    List<GeneratedJavaSource> modernSources =
        generator.generate(mapper.map(semanticModel, JavaMappingMode.MODERN));
    List<GeneratedJavaSource> allSources = new ArrayList<>();
    allSources.addAll(legacySources);
    allSources.addAll(modernSources);

    assertEquals(
        List.of(
            "hello/Greeter.java",
            "hello/GreeterHelper.java",
            "hello/GreeterHolder.java",
            "hello/GreeterPOA.java",
            "hello/_GreeterStub.java"),
        sourcePaths(legacySources));
    assertEquals(List.of("modern/hello/Greeter.java"), sourcePaths(modernSources));
    GoldenAssertions.assertTextEquals(
        "hello legacy Greeter",
        goldenFixtures().readUtf8("hello/legacy/hello/Greeter.java"),
        sourceText(legacySources, "hello/Greeter.java"));
    GoldenAssertions.assertTextEquals(
        "hello modern Greeter",
        goldenFixtures().readUtf8("hello/modern/modern/hello/Greeter.java"),
        sourceText(modernSources, "modern/hello/Greeter.java"));
    assertNoForbiddenGeneratedSourceTokens(
        allSources.stream().map(GeneratedJavaSource::sourceText).reduce("", String::concat));
    compile(allSources);
  }

  @Test
  void generatesCompileSafeSourcesFromApprovedRmiGeneratedIdlFixture() throws Exception {
    IdlSemanticModel semanticModel = semanticModel("rmi-generated.idl", rmiGeneratedIdlFixture());

    List<GeneratedJavaSource> sources =
        generator.generate(mapper.map(semanticModel, JavaMappingMode.LEGACY_COMPATIBILITY));

    assertEquals(
        List.of(
            "example/calc/Calculator.java",
            "example/calc/CalculatorHelper.java",
            "example/calc/CalculatorHolder.java",
            "example/calc/CalculatorPOA.java",
            "example/calc/CalculatorProblem.java",
            "example/calc/CalculatorProblemHelper.java",
            "example/calc/CalculatorProblemHolder.java",
            "example/calc/_CalculatorStub.java"),
        sourcePaths(sources));
    GoldenAssertions.assertTextEquals(
        "RMI generated IDL Calculator",
        """
        // Generated by mundane-java-orb G6-160.
        // Source IDL: rmi-generated.idl
        // Mapping mode: LEGACY_COMPATIBILITY
        // Compatibility profile: compile-safe minimal IDL-to-Java slice.

        package example.calc;

        public interface Calculator {

          int add(int left, int right);

          java.lang.String describe(java.lang.String name) throws example.calc.CalculatorProblem;

          void clear();
        }
        """,
        sourceText(sources, "example/calc/Calculator.java"));
    assertNoForbiddenGeneratedSourceTokens(
        sources.stream().map(GeneratedJavaSource::sourceText).reduce("", String::concat));
    compile(sources);
  }

  @Test
  void generatedSourceValuesValidateAndExposePaths() {
    GeneratedJavaSource source = new GeneratedJavaSource("demo", "Thing", "package demo;\n");
    GeneratedJavaSource defaultPackageSource =
        new GeneratedJavaSource("", "Root", "class Root {}\n");

    assertEquals("demo/Thing.java", source.sourcePath());
    assertEquals("Root.java", defaultPackageSource.sourcePath());
    assertEquals(new GeneratedJavaSource("demo", "Thing", "package demo;\n"), source);
    assertThrows(
        NullPointerException.class, () -> new GeneratedJavaSource(null, "X", "class X {}\n"));
    assertThrows(
        IllegalArgumentException.class, () -> new GeneratedJavaSource("demo", " ", "class X {}\n"));
    assertThrows(
        IllegalArgumentException.class, () -> new GeneratedJavaSource("", "", "class X {}\n"));
    assertThrows(IllegalArgumentException.class, () -> new GeneratedJavaSource("", "X", " "));
  }

  @Test
  void generatedSourcesAvoidConstantHolderNameCollisions() throws Exception {
    IdlSemanticModel semanticModel =
        semanticModel(
            """
            module Demo {
              const long VALUE = 1;
              struct IdlConstants { long x; };
            };
            """);

    List<GeneratedJavaSource> sources =
        generator.generate(mapper.map(semanticModel, JavaMappingMode.LEGACY_COMPATIBILITY));

    assertEquals(
        List.of(
            "demo/IdlConstants.java",
            "demo/IdlConstantsHelper.java",
            "demo/IdlConstantsHolder.java",
            "demo/IdlConstants_.java"),
        sources.stream().map(GeneratedJavaSource::sourcePath).toList());
    compile(sources);
  }

  @Test
  void generatesCompileSafeLegacyG10Surfaces() throws Exception {
    List<GeneratedJavaSource> sources =
        generator.generate(
            mapper.map(
                semanticModel("g10-peer.idl", g10PeerStyleIdl()),
                JavaMappingMode.LEGACY_COMPATIBILITY));

    assertEquals(
        List.of(
            "g10/Base.java",
            "g10/BaseHelper.java",
            "g10/BaseHolder.java",
            "g10/BasePOA.java",
            "g10/Choice.java",
            "g10/ChoiceHelper.java",
            "g10/ChoiceHolder.java",
            "g10/Count.java",
            "g10/CountHelper.java",
            "g10/CountHolder.java",
            "g10/Forward.java",
            "g10/ForwardHelper.java",
            "g10/ForwardHolder.java",
            "g10/IdlConstants.java",
            "g10/Matrix.java",
            "g10/MatrixHelper.java",
            "g10/MatrixHolder.java",
            "g10/Names.java",
            "g10/NamesHelper.java",
            "g10/NamesHolder.java",
            "g10/Problem.java",
            "g10/ProblemHelper.java",
            "g10/ProblemHolder.java",
            "g10/Sequence_string_32__Holder.java",
            "g10/Service.java",
            "g10/ServiceHelper.java",
            "g10/ServiceHolder.java",
            "g10/ServicePOA.java",
            "g10/_BaseStub.java",
            "g10/_ServiceStub.java"),
        sourcePaths(sources));
    String service = sourceText(sources, "g10/Service.java");
    assertContains(service, "public interface Service extends g10.Base, g10.Forward");
    assertContains(
        service,
        "void submit(java.lang.String[] names, g10.ChoiceHolder result, g10.CountHolder count) throws g10.Problem;");
    assertContains(service, "void collect(g10.Sequence_string_32__Holder values);");
    assertContains(sourceText(sources, "g10/CountHolder.java"), "public int value;");
    assertContains(
        sourceText(sources, "g10/Sequence_string_32__Holder.java"),
        "public java.lang.String[] value;");
    assertContains(
        sourceText(sources, "g10/_ServiceStub.java"), "public abstract class _ServiceStub");
    assertNoForbiddenGeneratedSourceTokens(
        sources.stream().map(GeneratedJavaSource::sourceText).reduce("", String::concat));
    compile(sources);
  }

  @Test
  void generatesCompileSafeLegacyAndModernG12RicherSurfaces() throws Exception {
    IdlSemanticModel semanticModel = semanticModel("g12-rich.idl", g12RicherIdl());
    List<GeneratedJavaSource> legacySources =
        generator.generate(mapper.map(semanticModel, JavaMappingMode.LEGACY_COMPATIBILITY));
    List<GeneratedJavaSource> modernSources =
        generator.generate(mapper.map(semanticModel, JavaMappingMode.MODERN));
    List<GeneratedJavaSource> allSources = new ArrayList<>();
    allSources.addAll(legacySources);
    allSources.addAll(modernSources);

    assertEquals(
        List.of(
            "g12/AbstractBase.java",
            "g12/AbstractBaseHelper.java",
            "g12/AbstractBaseHolder.java",
            "g12/AbstractBasePOA.java",
            "g12/BaseValue.java",
            "g12/BaseValueHelper.java",
            "g12/BaseValueHolder.java",
            "g12/Handle.java",
            "g12/HandleHelper.java",
            "g12/HandleHolder.java",
            "g12/NameValue.java",
            "g12/NameValueHelper.java",
            "g12/NameValueHolder.java",
            "g12/Problem.java",
            "g12/ProblemHelper.java",
            "g12/ProblemHolder.java",
            "g12/ValueThing.java",
            "g12/ValueThingHelper.java",
            "g12/ValueThingHolder.java",
            "g12/_AbstractBaseStub.java"),
        sourcePaths(legacySources));
    assertEquals(
        List.of(
            "modern/g12/AbstractBase.java",
            "modern/g12/BaseValue.java",
            "modern/g12/Handle.java",
            "modern/g12/NameValue.java",
            "modern/g12/Problem.java",
            "modern/g12/ValueThing.java"),
        sourcePaths(modernSources));

    String valueThing = sourceText(legacySources, "g12/ValueThing.java");
    assertContains(
        valueThing, "public class ValueThing extends g12.BaseValue implements g12.AbstractBase");
    assertContains(valueThing, "public final int id;");
    assertContains(valueThing, "public final java.lang.String[] names;");
    assertContains(valueThing, "public static g12.ValueThing create(int id) throws g12.Problem");
    assertContains(valueThing, "public void touch(g12.Handle handle)");
    assertContains(
        sourceText(legacySources, "g12/BaseValue.java"), "public abstract class BaseValue");
    assertContains(
        sourceText(legacySources, "g12/ValueThingHelper.java"),
        "private static final String ID = \"IDL:example.com/G12/ValueThing:1.0\";");
    assertContains(
        sourceText(legacySources, "g12/NameValue.java"), "public final java.lang.String value;");
    assertContains(sourceText(legacySources, "g12/Handle.java"), "private Handle() {}");
    assertNoForbiddenGeneratedSourceTokens(
        allSources.stream().map(GeneratedJavaSource::sourceText).reduce("", String::concat));
    compile(allSources);
  }

  @Test
  void g12WideInteropCorpusParsesMapsAndCompilesGeneratedSources() throws Exception {
    JavaDescriptorSourceGenerator descriptorGenerator = new JavaDescriptorSourceGenerator();
    Path corpus = findRepositoryRoot().resolve("interop/idl/g12-wide");
    List<String> supportedFixtures =
        List.of("CoreTypes.idl", "RepositoryPragmas.idl", "ValueTypes.idl");

    for (String fixture : supportedFixtures) {
      IdlSemanticModel semanticModel =
          semanticModel(fixture, Files.readString(corpus.resolve(fixture), StandardCharsets.UTF_8));
      List<GeneratedJavaSource> sources = new ArrayList<>();
      sources.addAll(
          generator.generate(mapper.map(semanticModel, JavaMappingMode.LEGACY_COMPATIBILITY)));
      sources.addAll(
          descriptorGenerator.generate(semanticModel, JavaMappingMode.LEGACY_COMPATIBILITY));

      assertNoForbiddenGeneratedSourceTokens(
          sources.stream().map(GeneratedJavaSource::sourceText).reduce("", String::concat));
      compile(sources);
    }

    IdlSemanticModel unsupported =
        semanticModel(
            "UnsupportedCustomValue.idl",
            Files.readString(corpus.resolve("UnsupportedCustomValue.idl"), StandardCharsets.UTF_8));
    IllegalArgumentException exception =
        assertThrows(
            IllegalArgumentException.class,
            () -> mapper.map(unsupported, JavaMappingMode.LEGACY_COMPATIBILITY));

    assertEquals(
        "Unsupported IDL-to-Java mapping: custom valuetype ::WideUnsupported::CustomValue",
        exception.getMessage());
  }

  @Test
  void rejectsDuplicateGeneratedSourcePaths() {
    JavaMappingModel model =
        new JavaMappingModel(
            JavaMappingMode.LEGACY_COMPATIBILITY,
            "duplicate.idl",
            List.of(
                new JavaMappedType(
                    JavaMappedTypeKind.STRUCT,
                    new JavaMappedName("demo", "Thing"),
                    List.of(),
                    List.of(),
                    List.of(),
                    List.of())),
            List.of(
                new JavaMappedConstantScope(
                    new JavaMappedName("demo", "Thing"),
                    List.of(new JavaMappedConstant("int", "VALUE", "1")))));

    IllegalArgumentException exception =
        assertThrows(IllegalArgumentException.class, () -> generator.generate(model));
    assertEquals("Duplicate generated Java source path: demo/Thing.java", exception.getMessage());
  }

  private JavaMappingModel mapping(JavaMappingMode mode) {
    return mapper.map(semanticModel(), mode);
  }

  private IdlSemanticModel semanticModel() {
    return semanticModel(
        """
        module Demo {
          const long BASE = 7;
          enum Color { RED, GREEN };
          const Color FAVORITE = Color::GREEN;
          struct Point { long x; string label; };
          exception Bad { string reason; };
          interface Shape {
            readonly attribute string name;
            attribute long size;
            Point move(in Point value, out long count) raises (Bad);
          };
        };
        """);
  }

  private IdlSemanticModel semanticModel(String source) {
    return semanticModel("codegen-test.idl", source);
  }

  private IdlSemanticModel semanticModel(String sourceName, String source) {
    IdlParseResult parseResult = parser.parse(sourceName, source);
    assertFalse(parseResult.hasErrors(), () -> parseResult.diagnostics().toString());
    IdlSemanticResult semanticResult =
        analyzer.analyze(parseResult.translationUnit().orElseThrow());
    assertFalse(semanticResult.hasErrors(), () -> semanticResult.diagnostics().toString());
    return semanticResult.model().orElseThrow();
  }

  private static List<String> sourcePaths(List<GeneratedJavaSource> sources) {
    return sources.stream().map(GeneratedJavaSource::sourcePath).toList();
  }

  private static String sourceText(List<GeneratedJavaSource> sources, String sourcePath) {
    return sources.stream()
        .filter(source -> source.sourcePath().equals(sourcePath))
        .findFirst()
        .orElseThrow()
        .sourceText();
  }

  private static void assertNoForbiddenGeneratedSourceTokens(String sourceText) {
    List<String> violations =
        FORBIDDEN_GENERATED_SOURCE_TOKENS.stream().filter(sourceText::contains).toList();

    assertEquals(List.of(), violations, "Generated source contains forbidden architecture tokens");
  }

  private static void assertContains(String text, String expected) {
    assertEquals(true, text.contains(expected), () -> "Missing generated text: " + expected);
  }

  private static FixtureSet idlFixtures() {
    return new FixtureSet(findRepositoryRoot().resolve("interop/idl"));
  }

  private static FixtureSet goldenFixtures() throws Exception {
    URL resource = JavaSourceGeneratorTest.class.getResource("/golden-source");
    assertNotNull(resource, "golden-source test resource root");
    return new FixtureSet(Path.of(resource.toURI()));
  }

  private static String rmiGeneratedIdlFixture() throws Exception {
    return Files.readString(
        findRepositoryRoot()
            .resolve("modules/corba-rmi-iiop/src/test/resources/rmi-generated-idl/calculator.idl"));
  }

  private static String g10PeerStyleIdl() {
    return """
        module G10 {
          const unsigned long LIMIT = 4;
          interface Forward;
          typedef sequence<string<32>, LIMIT> Names;
          typedef long Matrix[2][LIMIT], Count;
          union Choice switch (long) {
            case 0:
            case 1: string<16> text;
            default: Names names;
          };
          exception Problem { string reason; };
          interface Base { void ping(); };
          interface Service : Base, Forward {
            attribute Count counts[LIMIT];
            void submit(in Names names, out Choice result, inout Count count) raises (Problem);
            void collect(out sequence<string<32>> values);
          };
        };
        """;
  }

  private static String g12RicherIdl() {
    return """
        #pragma prefix "example.com"
        module G12 {
          native Handle;
          exception Problem {};
          abstract interface AbstractBase {};
          valuetype NameValue string<32>;
          abstract valuetype BaseValue {};
          valuetype ValueThing : BaseValue supports AbstractBase {
            public long id;
            private sequence<string, 8> names;
            factory create(in long id) raises (Problem);
            void touch(in Handle handle);
          };
          typeprefix BaseValue "example.com/G12";
          typeprefix ValueThing "example.com/G12";
        };
        """;
  }

  private static Path findRepositoryRoot() {
    Path directory = Path.of("").toAbsolutePath().normalize();
    while (directory != null) {
      if (Files.isRegularFile(directory.resolve("AGENT.md"))
          && Files.isDirectory(directory.resolve("modules"))) {
        return directory;
      }
      directory = directory.getParent();
    }
    throw new IllegalStateException("Could not locate repository root from test working directory");
  }

  private void compile(List<GeneratedJavaSource> sources) throws Exception {
    Path sourceRoot = Files.createDirectories(tempDir.resolve("generated-src"));
    Path classOutput = Files.createDirectories(tempDir.resolve("generated-classes"));
    List<String> arguments = new ArrayList<>();
    arguments.add("-d");
    arguments.add(classOutput.toString());
    for (GeneratedJavaSource source : sources) {
      Path sourceFile = sourceRoot.resolve(source.sourcePath());
      Path parent = sourceFile.getParent();
      if (parent != null) {
        Files.createDirectories(parent);
      }
      Files.writeString(sourceFile, source.sourceText(), StandardCharsets.UTF_8);
      arguments.add(sourceFile.toString());
    }

    JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
    assertNotNull(compiler, "Generated-source compilation requires a JDK compiler");
    assertEquals(0, compiler.run(null, null, null, arguments.toArray(String[]::new)));
  }
}
