[versions]
javaBaseline = "21"
junit = "6.0.3"
archunit = "1.4.2"
jacoco = "0.8.14"
spotlessPlugin = "8.5.1"
spotbugs = "4.9.8"
spotbugsPlugin = "6.5.4"
checkstyle = "13.4.2"
errorpronePlugin = "5.1.0"
errorprone = "2.49.0"
graalvmNativePlugin = "1.1.0"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotlessPlugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugsPlugin" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorpronePlugin" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvmNativePlugin" }
