// Generated by mundane-java-orb G6-160.
// Source IDL: hello/hello.idl
// Mapping mode: LEGACY_COMPATIBILITY
// Compatibility profile: compile-safe minimal IDL-to-Java slice.

package hello;

public interface Greeter {

  java.lang.String greet(java.lang.String name);
}
