package io.github.mundanej.mjo.codegen;

import io.github.mundanej.mjo.idl.java.mapping.JavaMappedAttribute;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedConstant;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedConstantScope;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedField;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedOperation;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedParameter;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappedType;
import io.github.mundanej.mjo.idl.java.mapping.JavaMappingModel;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;

/** Renders deterministic compile-safe Java source from a Java mapping model. */
public final class JavaSourceGenerator {

  /** Creates a stateless source generator. */
  public JavaSourceGenerator() {}

  /** Generates Java sources sorted by deterministic relative source path. */
  public List<GeneratedJavaSource> generate(JavaMappingModel model) {
    Objects.requireNonNull(model, "model");
    List<GeneratedJavaSource> sources = new ArrayList<>();
    for (JavaMappedConstantScope constantScope : model.constantScopes()) {
      sources.add(renderConstants(model, constantScope));
    }
    for (JavaMappedType type : model.types()) {
      sources.add(renderType(model, type));
    }
    List<GeneratedJavaSource> sorted =
        sources.stream().sorted(Comparator.comparing(GeneratedJavaSource::sourcePath)).toList();
    assertUniqueSourcePaths(sorted);
    return sorted;
  }

  private static void assertUniqueSourcePaths(List<GeneratedJavaSource> sources) {
    Set<String> paths = new HashSet<>();
    for (GeneratedJavaSource source : sources) {
      if (!paths.add(source.sourcePath())) {
        throw new IllegalArgumentException(
            "Duplicate generated Java source path: " + source.sourcePath());
      }
    }
  }

  private GeneratedJavaSource renderConstants(
      JavaMappingModel model, JavaMappedConstantScope constantScope) {
    StringBuilder source = header(model, constantScope.name().packageName());
    source
        .append("public final class ")
        .append(constantScope.name().simpleName())
        .append(" {\n\n")
        .append("  private ")
        .append(constantScope.name().simpleName())
        .append("() {}\n\n");
    for (JavaMappedConstant constant : constantScope.constants()) {
      source
          .append("  public static final ")
          .append(constant.javaType())
          .append(' ')
          .append(constant.name())
          .append(" = ")
          .append(constant.initializer())
          .append(";\n");
    }
    source.append("}\n");
    return new GeneratedJavaSource(
        constantScope.name().packageName(), constantScope.name().simpleName(), source.toString());
  }

  private GeneratedJavaSource renderType(JavaMappingModel model, JavaMappedType type) {
    StringBuilder source = header(model, type.name().packageName());
    switch (type.kind()) {
      case INTERFACE -> renderInterface(source, type);
      case STRUCT -> renderStruct(source, type);
      case ENUM -> renderEnum(source, type);
      case EXCEPTION -> renderException(source, type);
    }
    return new GeneratedJavaSource(
        type.name().packageName(), type.name().simpleName(), source.toString());
  }

  private StringBuilder header(JavaMappingModel model, String packageName) {
    StringBuilder source = new StringBuilder();
    source
        .append("// Generated by mundane-java-orb G6-160.\n")
        .append("// Source IDL: ")
        .append(model.sourceName())
        .append("\n")
        .append("// Mapping mode: ")
        .append(model.mode())
        .append("\n")
        .append("// Compatibility profile: compile-safe minimal IDL-to-Java slice.\n\n");
    if (!packageName.isEmpty()) {
      source.append("package ").append(packageName).append(";\n\n");
    }
    return source;
  }

  private static void renderInterface(StringBuilder source, JavaMappedType type) {
    source.append("public interface ").append(type.name().simpleName()).append(" {\n");
    for (JavaMappedAttribute attribute : type.attributes()) {
      String accessorSuffix = accessorSuffix(attribute.name());
      source
          .append("\n  ")
          .append(attribute.javaType())
          .append(" get")
          .append(accessorSuffix)
          .append("();\n");
      if (!attribute.readonly()) {
        source
            .append("\n  void set")
            .append(accessorSuffix)
            .append('(')
            .append(attribute.javaType())
            .append(' ')
            .append(attribute.name())
            .append(");\n");
      }
    }
    for (JavaMappedOperation operation : type.operations()) {
      source
          .append("\n  ")
          .append(operation.returnType())
          .append(' ')
          .append(operation.name())
          .append('(');
      source.append(
          operation.parameters().stream()
              .map(JavaSourceGenerator::parameter)
              .collect(Collectors.joining(", ")));
      source.append(')');
      if (!operation.thrownTypes().isEmpty()) {
        source.append(" throws ").append(String.join(", ", operation.thrownTypes()));
      }
      source.append(";\n");
    }
    source.append("}\n");
  }

  private static void renderStruct(StringBuilder source, JavaMappedType type) {
    source.append("public final class ").append(type.name().simpleName()).append(" {\n");
    renderFields(source, type.fields());
    renderConstructor(source, type.name().simpleName(), type.fields(), false);
    source.append("}\n");
  }

  private static void renderEnum(StringBuilder source, JavaMappedType type) {
    source.append("public enum ").append(type.name().simpleName()).append(" {\n");
    for (int index = 0; index < type.enumConstants().size(); index++) {
      String terminator = index == type.enumConstants().size() - 1 ? ";" : ",";
      source.append("  ").append(type.enumConstants().get(index)).append(terminator).append('\n');
    }
    source.append("}\n");
  }

  private static void renderException(StringBuilder source, JavaMappedType type) {
    source
        .append("public class ")
        .append(type.name().simpleName())
        .append(" extends java.lang.Exception {\n\n")
        .append("  private static final long serialVersionUID = 1L;\n");
    renderFields(source, type.fields());
    renderConstructor(source, type.name().simpleName(), type.fields(), true);
    source.append("}\n");
  }

  private static void renderFields(StringBuilder source, List<JavaMappedField> fields) {
    for (JavaMappedField field : fields) {
      source
          .append("\n  public final ")
          .append(field.javaType())
          .append(' ')
          .append(field.name())
          .append(";\n");
    }
  }

  private static void renderConstructor(
      StringBuilder source, String simpleName, List<JavaMappedField> fields, boolean exception) {
    source.append("\n  public ").append(simpleName).append('(');
    source.append(
        fields.stream().map(JavaSourceGenerator::fieldParameter).collect(Collectors.joining(", ")));
    source.append(") {\n");
    if (exception) {
      source.append("    super();\n");
    }
    for (JavaMappedField field : fields) {
      source
          .append("    this.")
          .append(field.name())
          .append(" = ")
          .append(field.name())
          .append(";\n");
    }
    source.append("  }\n");
  }

  private static String parameter(JavaMappedParameter parameter) {
    return parameter.javaType() + " " + parameter.name();
  }

  private static String fieldParameter(JavaMappedField field) {
    return field.javaType() + " " + field.name();
  }

  private static String accessorSuffix(String name) {
    return Character.toUpperCase(name.charAt(0)) + name.substring(1);
  }
}
